"""
    DO NOT COMMIT THIS FILE WITH INFORMATION FILLED OUT!
    DO NOT COMMIT THIS FILE WITH INFORMATION FILLED OUT!
    DO NOT COMMIT THIS FILE WITH INFORMATION FILLED OUT!
    DO NOT COMMIT THIS FILE WITH INFORMATION FILLED OUT!
"""

DB_USERNAME = ''
DB_PASSWORD = ''
SECRET_KEY = ''
