# Generated by Django 3.0.4 on 2020-04-01 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteraction',
            name='ended',
        ),
    ]
