# Generated by Django 3.0.4 on 2020-04-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_remove_userinteraction_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='meet_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
